Lint and fix docker (compose) files and run scripts in bash strict mode

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,4 +1,4 @@
-# syntax=docker/dockerfile:1.17
+# syntax=docker/dockerfile:1.21
 # check=error=true;skip=SecretsUsedInArgOrEnv
 # The first line fixes the Dockerfile frontend used by BuildKit. For details
 # see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
@@ -9,26 +9,45 @@
 # https://hub.docker.com/_/microsoft-dotnet-sdk
 # https://mcr.microsoft.com/artifact/mar/dotnet/sdk/tags
 FROM mcr.microsoft.com/dotnet/sdk:10.0-noble-amd64
+SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]
 
 ARG GROUP_ID
 ARG USER_ID
 ARG CERTIFICATE_AUTHORITY_BASE_FILE_NAME
 ARG CERTIFICATE_AUTHORITY_PASSWORD
 
+RUN \
+  if [ -z "$GROUP_ID" ]; then echo "required 'GROUP_ID'"; exit 1; fi && \
+  if [ -z "$USER_ID" ]; then echo "required 'USER_ID'"; exit 1; fi && \
+  if [ -z "$CERTIFICATE_AUTHORITY_BASE_FILE_NAME" ]; then echo "required 'CERTIFICATE_AUTHORITY_BASE_FILE_NAME'"; exit 1; fi && \
+  if [ -z "$CERTIFICATE_AUTHORITY_PASSWORD" ]; then echo "required 'CERTIFICATE_AUTHORITY_PASSWORD'"; exit 1; fi
+
 # Create non-root user to run commands in (see https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)
-# id --user --name ${USER_ID} 2>/dev/null
+# id --user --name "${USER_ID}" 2>/dev/null
 RUN \
   apt-get update && \
   apt-get install \
     --assume-yes \
     --no-install-recommends \
     adduser && \
-  existing_user_name="$(getent passwd ${USER_ID} 2>/dev/null | cut --delimiter=: --fields=1)" && \
-  if test -n "${existing_user_name}"; then deluser "${existing_user_name}"; fi && \
-  existing_group_name="$(getent group ${GROUP_ID} 2>/dev/null | cut --delimiter=: --fields=1)" && \
-  if test -n "${existing_group_name}"; then delgroup "${existing_group_name}"; fi && \
-  addgroup --system --gid ${GROUP_ID} us && \
-  adduser --system --home /home/me --uid ${USER_ID} --ingroup us me && \
+  existing_user_name="$( (getent passwd ${USER_ID} 2>/dev/null || true) | cut --delimiter=: --fields=1)" && \
+  if test -n "${existing_user_name}"; then \
+    deluser "${existing_user_name}"; \
+  fi && \
+  existing_group_name="$( (getent group ${GROUP_ID} 2>/dev/null || true) | cut --delimiter=: --fields=1)" && \
+  if test -n "${existing_group_name}"; then \
+    delgroup "${existing_group_name}"; \
+  fi && \
+  addgroup \
+    --system \
+    --gid "${GROUP_ID}" \
+    us && \
+  adduser \
+    --system \
+    --home /home/me \
+    --uid "${USER_ID}" \
+    --ingroup us \
+    me && \
   apt-get remove \
     --assume-yes \
     adduser && \
@@ -99,7 +118,7 @@ RUN \
 # See also https://github.com/dotnet/aspnetcore/issues/7246#issuecomment-541201757
 # and https://github.com/dotnet/runtime/issues/31237#issuecomment-544929504
 COPY \
-  ./ssl/${CERTIFICATE_AUTHORITY_BASE_FILE_NAME}.crt \
+  "./ssl/${CERTIFICATE_AUTHORITY_BASE_FILE_NAME}.crt" \
   /usr/local/share/ca-certificates
 RUN \
   update-ca-certificates
@@ -110,10 +129,11 @@ RUN \
 # Keep the version in sync with the one in the other Dockerfiles of this
 # repository and with the one of the `machine` repository specified in the
 # `local.yml` Ansible script.
-ENV GNUPG_VERSION=2.5.16-1
+ENV GNUPG_VERSION=2.5.17-1
 ENV GNUPG_FINGERPRINT=32097B719B3745D6E61DDA1B85C45AE3E1A2B355
-RUN set -eux && \
-  version_codename=$(env --ignore-environment bash -c '. /etc/os-release; echo $VERSION_CODENAME') && \
+# hadolint ignore=SC2016 # Ignore "Expressions don't expand in single quotes, use double quotes for that" because we do not want `$VERSION_CODENAME` to expand.
+RUN \
+  version_codename="$(env --ignore-environment bash -c '. /etc/os-release; echo $VERSION_CODENAME')" && \
   apt-get update && \
   apt-get install \
     --assume-yes \
@@ -123,7 +143,7 @@ RUN set -eux && \
   curl \
     --silent \
     --show-error \
-    https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg \
+    "https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg" \
     | gpg --dearmor \
     > /usr/share/keyrings/gnupg-keyring.gpg && \
   fingerprint=$(gpg \
@@ -143,7 +163,7 @@ RUN set -eux && \
     --assume-yes \
     --no-install-recommends \
     dirmngr \
-    gnupg2=${GNUPG_VERSION} && \
+    gnupg2="${GNUPG_VERSION}" && \
   rm \
     --recursive \
     --force \
@@ -151,14 +171,14 @@ RUN set -eux && \
 
 ENV HOME=/home/me
 RUN \
-  mkdir --parents ${HOME}/app && \
+  mkdir --parents "${HOME}/app" && \
   chown \
     me:us \
-    ${HOME} && \
+    "${HOME}" && \
   chown \
     me:us \
-    ${HOME}/app && \
-  ln --symbolic ${HOME}/app /app
+    "${HOME}/app" && \
+  ln --symbolic "${HOME}/app" /app
 
 ###########
 # As `me` #
@@ -345,19 +365,20 @@ RUN \
   mkdir ./ssl
 COPY \
   --chown=me:us \
-  ./ssl/${CERTIFICATE_AUTHORITY_BASE_FILE_NAME}.pfx \
+  "./ssl/${CERTIFICATE_AUTHORITY_BASE_FILE_NAME}.pfx" \
   ./ssl/
 RUN \
   dotnet tool run \
     certificate-tool add \
-      --file ./ssl/${CERTIFICATE_AUTHORITY_BASE_FILE_NAME}.pfx \
+      --file "./ssl/${CERTIFICATE_AUTHORITY_BASE_FILE_NAME}.pfx" \
       --store-name Root \
-      --password ${CERTIFICATE_AUTHORITY_PASSWORD}
+      --password "${CERTIFICATE_AUTHORITY_PASSWORD}"
 
 # bash parameter completion for the dotnet CLI
 # see https://learn.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#bash
 # for the here-document syntax used to append to the ~/.bashrc file
 # see https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07_04
+# hadolint ignore=DL3059 # Multiple consecutive `RUN` instructions.
 RUN \
   cat <<-"EOT" >> ${HOME}/.bashrc
 		function _dotnet_bash_complete()
@@ -392,17 +413,17 @@ RUN \
     ./test/bin \
     ./test/obj && \
   mkdir --parents \
-    ${HOME}/.vscode-server \
-    ${HOME}/.vscode-server-insiders && \
+    "${HOME}/.vscode-server" \
+    "${HOME}/.vscode-server-insiders" && \
   mkdir --parents \
-    ${HOME}/.nuget \
-    ${HOME}/.dotnet && \
+    "${HOME}/.nuget" \
+    "${HOME}/.dotnet" && \
   mkdir --parents \
-    ${HOME}/.gnupg && \
+    "${HOME}/.gnupg" && \
   chmod u=rwx,g=,o= \
-    ${HOME}/.gnupg && \
+    "${HOME}/.gnupg" && \
   echo "allow-loopback-pinentry" \
-    > ${HOME}/.gnupg/gpg-agent.conf
+    > "${HOME}/.gnupg/gpg-agent.conf"
 
 ENV SHELL=/bin/bash
 
