Improve GnuPG installation, in particular, check the key fingerprint to fend off man-in-the-middle attacks

diff --git a/backend/Dockerfile-bootstrap b/backend/Dockerfile-bootstrap
--- a/backend/Dockerfile-bootstrap
+++ b/backend/Dockerfile-bootstrap
@@ -19,9 +19,14 @@ RUN \
   addgroup --system --gid ${GROUP_ID} us && \
   adduser --system --uid ${USER_ID} --ingroup us me
 
-# Install up-to-date GnuPG from the official GnuPG repository
+# Install up-to-date GnuPG from the official GnuPG repository.
 # For available versions see https://repos.gnupg.org/deb/gnupg/
+# The fingerprint was taken from https://repos.gnupg.org/deb/gnupg/bookworm/
+# Keep the version in sync with the one in the other Dockerfiles of this
+# repository and with the one of the `machine` repository specified in the
+# `local.yml` Ansible script.
 ENV GNUPG_VERSION=2.4.8-2
+ENV GNUPG_FINGERPRINT=32097B719B3745D6E61DDA1B85C45AE3E1A2B355
 RUN set -eux && \
   version_codename=$(env --ignore-environment bash -c '. /etc/os-release; echo $VERSION_CODENAME') && \
   apt-get update && \
@@ -36,6 +41,16 @@ RUN set -eux && \
     https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg \
     | gpg --dearmor \
     > /usr/share/keyrings/gnupg-keyring.gpg && \
+  fingerprint=$(gpg \
+    --batch \
+    --with-colons \
+    --import-options show-only \
+    --import /usr/share/keyrings/gnupg-keyring.gpg \
+    | awk -F':' '$1=="fpr"{print $10}') && \
+  if [ "${fingerprint}" != "${GNUPG_FINGERPRINT}" ]; then \
+      echo "Error: Key fingerprint mismatch, got ${fingerprint} and expected ${GNUPG_FINGERPRINT}"; \
+      exit 1; \
+  fi && \
   echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gnupg-keyring.gpg] https://repos.gnupg.org/deb/gnupg/${version_codename}/ ${version_codename} main" \
     > /etc/apt/sources.list.d/gnupg.list && \
   apt-get update && \
@@ -48,7 +63,7 @@ RUN set -eux && \
     --recursive \
     --force \
     /var/lib/apt/lists/*
-
+WORKDIR /app
 ENV HOME=/home/me
 RUN \
   mkdir --parents ${HOME} && \
